# Autogenerated wrapper script for Reactant_jll for aarch64-linux-gnu-cxx11-cuda_version+12.9-gpu+cuda-mode+opt
export fatbinary, libReactantExtra, libdevice, libnccl, libnvshmem_device, libnvshmem_host, nvshmem_bootstrap_uid, nvshmem_transport_ibrc, ptxas

JLLWrappers.@generate_wrapper_header("Reactant")
JLLWrappers.@declare_library_product(libReactantExtra, "libReactantExtra.so")
JLLWrappers.@declare_library_product(libnccl, "libnccl.so.2")
JLLWrappers.@declare_file_product(libnvshmem_device)
JLLWrappers.@declare_library_product(libnvshmem_host, "libnvshmem_host.so.3")
JLLWrappers.@declare_library_product(nvshmem_bootstrap_uid, "nvshmem_bootstrap_uid.so.3")
JLLWrappers.@declare_library_product(nvshmem_transport_ibrc, "nvshmem_transport_ibrc.so.3")
JLLWrappers.@declare_executable_product(fatbinary)
JLLWrappers.@declare_file_product(libdevice)
JLLWrappers.@declare_executable_product(ptxas)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libReactantExtra,
        "lib/libReactantExtra.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnccl,
        "lib/libnccl.so.2",
        nothing,
    )

    JLLWrappers.@init_file_product(
        libnvshmem_device,
        "lib/libnvshmem_device.bc",
    )

    JLLWrappers.@init_library_product(
        libnvshmem_host,
        "lib/libnvshmem_host.so.3",
        nothing,
    )

    JLLWrappers.@init_library_product(
        nvshmem_bootstrap_uid,
        "lib/nvshmem_bootstrap_uid.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        nvshmem_transport_ibrc,
        "lib/nvshmem_transport_ibrc.so.3",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        fatbinary,
        "lib/cuda/bin/fatbinary",
    )

    JLLWrappers.@init_file_product(
        libdevice,
        "lib/cuda/nvvm/libdevice/libdevice.10.bc",
    )

    JLLWrappers.@init_executable_product(
        ptxas,
        "lib/cuda/bin/ptxas",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
